### ISSUE TITLE
 require_once(firewall\Memcache.class.php): failed to open stream: No such file or directory in WAFPHP.php on line 115

### ISSUE THREAD

**Issue by yassersharaf** [ZoaChou/WAFPHP#3]
Hi
I have index.php and a firewall folder contains your project files and folders.
The index page contains this code:
require_once 'firewall/WAFPHP.php';
$wafPHP = WAFPHP\WAFPHP::getInstance();
$wafPHP->runCheck();
The result is:
 require_once(firewall\Memcache.class.php): failed to open stream: No such file or directory in WAFPHP.php on line 115

**Comment by ZoaChou** [comment]
@yassersharaf Have you change the file dir or other else in the project?if you do that,revert it back and try again.It means autoLoad couldn't require Memcache class automatic.Please tell me your php version and system info,I will try again to find out either environment or your code lead to that.it works fine under 5.6 and 5.3 base on my test.

**Comment by yassersharaf** [comment]
The Memcache file does not exist in the project

**Comment by ZoaChou** [comment]
It is auto load by function autoLoad on index.php line 106.Now it doesn't work on your code,may be cause by your php version don't support spl_autoload_register() or namespace,so please tell me your php version.Memcache file is here:https://github.com/ZoaChou/WAFPHP/blob/master/Lib/Model/Memcache.class.php

**Comment by ZoaChou** [comment]
Since you are not reply for a lot time and can't support any useful information to find out the problem,this issue will be close.
